OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-mpUs4fyYC32zB6W4efIs6U6sDHAW0QotRxrf5rDGPNAjW64m"
  base_url: "https://xiaoai.plus/v1"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"